### ISSUE TITLE
Implement on EasyUI

### ISSUE THREAD

**Issue by krosoftware** [NeXTs/Clusterize.js#101]
Hello
could someone help me to implement Clusterize on EasyUI datagrid, please?
I created example of datagrid here: http://code.reloado.com/oeasyrik1/85/edit
and I don' t know how to add clusterize there.
Thank you.

**Comment by NeXTs** [comment]
With EasyUI the only option is to use this http://www.jeasyui.com/demo/main/?plugin=Pagination

**Comment by krosoftware** [comment]
Yes I know but I meant to load all records at once and to scroll them smoothly..

**Comment by NeXTs** [comment]
It's not that easy because EasyUI rows aren't static.
Github's issues just not right place for such requests, it's intended most likely for issue-related topics. You could try your luck and ask for help on stackoverflow but I don't believe someone will be interested in doing this because honestly that's much of effort to combine these two plugins. Much better would be to ask EasyUI's contributors if it's possible to use EasyUI table the way you want (and not pagination)
