### ISSUE TITLE
Understanding blocks and clusters

### ISSUE THREAD

**Issue by x11x** [NeXTs/Clusterize.js#119]
Hi,
This library is a great idea and works well.
I have no specific issues yet, but I'm interested in the underlying "clustering" technique and how it can be incorporated into other projects, and also how I can better use this library.
I have been reading the code and I understand that rows are grouped into blocks and then blocks are grouped into clusters.
What is the reason for these 2 levels of grouping?
I guess it allows tuning for different performance scenarios, but I don't really understand how/why. I am interested in further explanation of how to choose rows_in_block and blocks_in_cluster, and why these 2 levels are necessary (couldn't we just have rows and clusters and a rows_in_cluster option?)
Thanks for the library and any advice you might be able to give.

**Comment by NeXTs** [comment]
Hey

At this moment, 2 years later after creating library I agree that those 2 levels might be redundant
That time it was just easier for me to imagine virtualization structure this way

Scheme:

```
Cluster:
    Block:
--------------------------- // list viewport starts
        row
        row
        row
--------------------------- // list viewport ends
        row
    Block:
        row
        row
        row
        row
    Block: // ← will trigger cluster change(to next one) once scroll position reached this point
        row
        row
        row
        row
```

Block contains rows.
Let's say visible height of list element (list viewport on scheme) is 500px, height of single row is 50px.
Amount of rows (sum of their height) in single block should be slightly more than list viewport.
11-12 should be enough in this case

This way single block fills full height of list viewport without having blank space.
But if we had only one block - it meant that we would have to replace the list (cluster) on EVERY scroll.
That's why we have many blocks. Multiple blocks are intended to reduce amount of DOM changes (cluster changes) on scrolling.
With multiple blocks, cluster will be changed to next one only when scroll position reaches beginning of last block (← sign on scheme).

That's why description of **rows_in_block** in docs says 
> Increase *(of rows_in_block property)* means browser will be more loaded *(will keep more DOM elements in memory)*, decrease means browser will have to update clusters more often.
