### ISSUE TITLE
clusterize.update() fails when there are repeated items

### ISSUE THREAD

**Issue by JVRibeiro** [NeXTs/Clusterize.js#126]
Hey!

I'm creating a web app that uses Clusterize. _Very cool plugin by the way. ;)_

My issue is when I want to remove some of its items through the app itself using JavaScript's `.splice()` method. I also use a `for` loop to update some items informations before calling `clusterize.update()`.

It goes fine when there are diferent items in the list and if the viewport is at the end of the list (even if repeated), but `clusterize.update()` fails if there are repeated items in the cluster **AND** if the viewport is **NOT** at the end of the list.

In this gif you can understand me better:
https://gfycat.com/gifs/detail/RewardingUglyBongo

_My english is still a work in progress. Corrections are welcome. :)_

**Comment by NeXTs** [comment]
Hello

Can you provide some demo on codepen?

**Comment by JVRibeiro** [comment]
Of course! I'm using a phone now, but in a few minutes I come back here with a Pen.

**Comment by JVRibeiro** [comment]
Here's the pen:
https://codepen.io/ovictorribeiro/pen/xPZrwo

I also made a special console to help you to help me. haha

**Comment by NeXTs** [comment]
thanks

ok, so this happens because after deletion you send EXACT same layout of current cluster.
clusterize has [additional check](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L262) to prevent unnecessary updates if layout wasn't changed

the only difference between rows after row number 80 is numbers. but after deletion you restoring numbers of subsequent rows. layout stored in clusterize cache and updated layout for current cluster are equal, that's why this condition fails for your case.

what you can do:

1. dirty but quick workaround.
after deletion - change your list at least somehow to give a hint for clusterize to update list.
here I've added data-update attribute, data property increments on every deletion so this should help. 
https://codepen.io/NeXTs/pen/rYxpbm?editors=1010

2. Wait until I publish update for clusterize (day or two) that would allow you to use pure css counters.

**Comment by JVRibeiro** [comment]
Oh thank you very much for the workaround and for the explanation (thanks for the redundance tip too, I'm not an example of good programmer).

I'll implement your solution temporarily. I'll wait for the update, though.

**Comment by NeXTs** [comment]
Hey @JVRibeiro 
see demo of "[Ordered list](https://clusterize.js.org/)"

**Comment by JVRibeiro** [comment]
Cool! That was pretty fast.

**Comment by FeehGb** [comment]
case Nothing change, could return something in callback ?
