### ISSUE TITLE
Demo: Scrolling laggier with clusterize than without it

### ISSUE THREAD

**Issue by EamonNerbonne** [NeXTs/Clusterize.js#13]
I'm using firefox on windows; scrolling 5000 rows without clusterize is perfectly smooth; with clusterize it's noticably laggy (at a rough estimate say 10fps).  Scrolling performance does remain consistent even with lots of rows.

**Comment by piotrcyr** [comment]
I observe the same effect with Firefox on Linux.

**Comment by NeXTs** [comment]
Scrolling 5000 may be smooth if you have powerfull PC, although in this case the plugin should run smoothly too, strange. I was forced to use 5000 rows in tutorial because of mobile users.
Try to set much more rows in playground to see the difference (Append -> Append... -> Destroy table inserts all rows to the table)
http://nexts.github.io/Clusterize.js/#playground

**Comment by influenza** [comment]
Chromium on Arch behaves as the demo expects. Scrolling without is painful, with clusterize is silky smooth.

**Comment by NeXTs** [comment]
Thank you influenza, hope others are experiencing the same effect, anyway there's nothing I can do to speed up DOM manipulations.

**Comment by zakius** [comment]
Demo is painfully slow (list viewport becomes blank) in Firefox and noticeably slow in Chrome with the `clusterize-content` class, removing it makes it work as expected. I'm not sure if it's actually needed there for anything, you may want to look into it @NeXTs
