### ISSUE TITLE
row rendering leaks with large amount of data

### ISSUE THREAD

**Issue by s-a** [NeXTs/Clusterize.js#31]
I am playing with clusterize in Github' s Electron environment and noticed that the row rendering leaks with large amount of data. A reproducible example is at https://github.com/s-a/fileSharp/tree/abc29f2b872bb53f07e5a20cc8c1905dd83f81ac.  The repo contains static test data (~8000 list items).  
It should start easy with  
```npm install;```
```npm run dev;``` Then switch to "test-folder" with a double click.

![image](https://cloud.githubusercontent.com/assets/1270662/8448471/539d5e50-1fc8-11e5-9086-ca7ab9d6b35f.png)

**Comment by NeXTs** [comment]
Hi Stephan,
that's same issue as [Martin noticed recently](https://github.com/NeXTs/Clusterize.js/issues/29)

That happens because you resized window and rows changed height.

I made [pull request](https://github.com/s-a/fileSharp/pull/1) with temporary workaround, this should work fine for you. And I'll notify you once I implement this behaviout input plugin.

**Comment by s-a** [comment]
Ty for quick help. I subscribed #29
