### ISSUE TITLE
Always keep top N items option and prevent animated scrolling

### ISSUE THREAD

**Issue by litera** [NeXTs/Clusterize.js#36]
Is there an option to always keep top *page* of items, as users can always hit the <kbd>Home</kbd> key? ~~At the moment whole list executes an animated scroll.~~ If list is supposed to be loaded asynchronously, this would make many unnecessary HTTP requests to the server while scrolling would have to be paused. Having top page always loaded could simply jump to the top of the list (and maybe just animate this portion as it should hold more than a visible page of items). but it would definitely prevent HTTP requests.

How should this be solved?

**Comment by NeXTs** [comment]
Hi Robert,

I am sorry but I didn't get your idea.

Clusterize doesn't support http requests, asynchronous loading logic and etc. It's intended to render rows. Think of it as 'view'.

Main idea is to create one array of rows (empty of filled with some initial data, no matter).
Init clusterize with this array. Make asynchronous request to load more rows, if needed.
Add loaded rows to our array and call clusterize_instance.update(our_array);

**Comment by litera** [comment]
I didn't imply that Clusterize does any *async magic*. I was thinking (for whatever reason) that clusterize only works with a subset of the whole data set. But that's not the case. Clusterize uses **the whole set** and only displays a specific cluster of rows at a time.

My original question was if there was any possibility to keep the first (and last) cluster always part of the DOM in case user hits the <kbd>Home</kbd> or <kbd>Enter</kbd> key? Because if we look at the possible scenarios of a long list user may either:
* scroll up (or down) whicm means that sooner or later clusterize will have to display a different cluster which is sibling to current one - in case user is scrolling down it will be next cluster, if scrolling up it will be previous
* hitting <kbd>PgUp</kbd>/<kbd>PhDown</kbd>/<kbd>Space</kbd> which is similar to first
* hitting <kbd>Home</kbd>/<kbd>End</kbd> which forces clusterize to display first/last cluster and recalculate dummy empty containers

Now if clusterize would always keep in DOM first, last and current cluster it wouldn't have to do any specific processing when third event would happen, which would result in an instant view it first/last cluster items.

But my question was also related to animated scrolling. Because if user hits the <kbd>Home</kbd> button and browser has some sort of animated scrolling feature, then browser will execute a series of `onscroll` events meaning there will be much more processing for each step in between current cluster and first one.

Did I explain myself better this time?

**Comment by NeXTs** [comment]
Thanks, now it's much clearer.

Regarding <kbd>Home</kbd> buttons question - It is slightly artificial problem. I don't really think that additional top/bottom clusters worth the effort. Cluster chunks are replaces so fast that user will not even notice this. Replacing of first or last cluster it's an ordinary action for this plugin. Moreover, it will pollute the DOM with redundant markup.

Animated scrolling - Look, if user has enabled smooth scrolling in his browser - this is the usual behaviour for him and I do not want to break this behaviour. I understand that because of the smooth scrolling may be made more DOM inserts (in series), than if the transition was instant. But the clusters are changing very quickly, so I'm willing to sacrifice performance to keep customary UI behaviour.
