### ISSUE TITLE
A way to hook into rendering events?

### ISSUE THREAD

**Issue by OscarGodson** [NeXTs/Clusterize.js#52]
We built a way to select rows in our table by clicking on them but we realized that when you resize the DOM gets rerendered and we lose our selected classes. `clusterChanged` doesn't seem to fire when this happens. Is there some event or something I can hook into whenever Clusterize rerenders?

**Comment by NeXTs** [comment]
Hi Oscar
`clusterChanged` must be called after every cluster-related "DOM manipulation", since [it's called](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L268) right after `.html` inserting

Make sure you use last version 0.14.0 and check syntax of defining callbacks:
```
var clusterize = new Clusterize({
  rows: data,
  scrollId: 'scrollArea',
  contentId: 'contentArea',
  callbacks: {
    clusterChanged: function() {
      console.log('Changed')
    }
  }
});
```

Does `clusterChanged` in [this demo](http://codepen.io/NeXTs/pen/vNvyVg?editors=101) works for you on resize?

**Comment by OscarGodson** [comment]
Appears I was on a slightly older version. After updating this worked perfectly. Thanks!
