### ISSUE TITLE
Do not reset cluster_number to 0

### ISSUE THREAD

**Issue by vamp** [NeXTs/Clusterize.js#58]
https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L131
better would be:
```
last_cluster = Math.floor(rows.length / (this.options.rows_in_cluster - this.options.rows_in_block));
```

**Comment by NeXTs** [comment]
Hi Denis
Why do you think so?

That workaround was made to fix issue #39. Pay attention to jumping scrollbar after clicking "Update". The problem was: if total height of new list is lower than scroll position (which means scroll position is somewhere at the bottom of list), then browser will scroll to position of last row, which will produle a lot of redundant scroll events, because we [listening](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L111) for scroll event and made some calculation when scroll fires.

Trick is to save scroll position [before update](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L127)
`var scroll_top = self.scroll_elem.scrollTop;`

then [check ](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L129) if total height of updated list is smaller than current scroll position...
`if(rows.length * self.options.item_height < scroll_top) {`

[forcibly](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L130) scroll position to zero
`self.scroll_elem.scrollTop = 0;`

[insert](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L133) new list to DOM
`self.insertToDOM(rows, cache);`

and finally [scroll](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L134) to previous position
`self.scroll_elem.scrollTop = scroll_top;`
as soon as actual list height is lower than saved scroll_top property from variable, browser will scroll to the end of the list. This way we avoid unneccesary scroll events.

[last_cluster](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L131) must be set to zero because at that moment scroll position is set to zero by [upper line](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L130), what means - there are very first cluster in the DOM. It's necessary for condition inside [scroll callback](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L101).

[Last line](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L134) `self.scroll_elem.scrollTop = scroll_top;` causes scroll event so scroll callback checks value received from `self.getClusterNum()` with our `last_cluster`. If values will be same then condition isn't met and last cluster does not [inserts to DOM](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L102).

That's why `last_cluster` should be reset to zero.
