### ISSUE TITLE
Feature Request: Add a method to scroll to row at index

### ISSUE THREAD

**Issue by zaygraveyard** [NeXTs/Clusterize.js#79]
Can you please add a method that scrolls to the row at a give index?

Possible implementation:
```js
scrollToRowAtIndex: function(index) {
  this.scroll_elem.scrollTop = index * this.options.item_height;
},
```

Thanks

**Comment by NeXTs** [comment]
it's not that straightforward feature because rows height may vary

there has been discussion by this topic already
https://github.com/NeXTs/Clusterize.js/issues/55#issuecomment-157914376

**Comment by zaygraveyard** [comment]
I see, but since this library requires rows with more or less the same height, I thought this method could be reasonable.

The alternative is to do it all from the outside as in the [last comment of #55](https://github.com/NeXTs/Clusterize.js/issues/55#issuecomment-162047861), but for me it feels like more elegant to have this method.

And it could become more exact with something like:
```js
clusterize.scrollToRowAtIndex(/* row index */);

// at this point the row is probably in the DOM
// scroll to it

var scrollAreaNode = /* get the scroll area node */;
var node = scrollAreaNode.querySelector(/*query to find the row node*/);
scrollAreaNode.scrollTop = node.offsetTop;
```

**Comment by zaygraveyard** [comment]
I forgot to mention all my rows have the exact same height so I would only need to all the method.

**Comment by NeXTs** [comment]
Hey there

[There already has been attempt](http://codepen.io/NeXTs/pen/VvRyJE?editors=101) to implement the idea you've proposed and it's not that easy as expected because row's height may vary way too much.

I can not add method which will work only in half of cases.

Since you say that your rows are same height, you could scroll the list by yourself as proposed in [last comment of #55](https://github.com/NeXTs/Clusterize.js/issues/55#issuecomment-162047861) and [FAQ](https://clusterize.js.org/#faq)

**Comment by aschilling** [comment]
I would be very much interessted in a solution as well. In particular, I have the problem that the divs I use with clusterize are by default different sizes, such that I cannot use the suggested solutions to scroll to the particular div.

**Comment by zaygraveyard** [comment]
@NeXTs I understand and thank you for the link.
