### ISSUE TITLE
Horizontal Lists

### ISSUE THREAD

**Issue by olsn** [NeXTs/Clusterize.js#8]
Hi,

I love your plugin!
Is support for horizontal lists planned in a future version?

cheers 
olsn

**Comment by NeXTs** [comment]
Hi Olaf, thank you!

It's seems a bit redundant, not every day we have to deal with as long horizontal lists. But I'll think about it if I have received a lot more of requests.

**Comment by zbjornson** [comment]
This would be useful for me. We have a large grid in both dimensions (horizontal and vertical).

**Comment by atcrawford** [comment]
+1

**Comment by BevanR** [comment]
➕ **1**

**Comment by pchr-srf** [comment]
+1 from me, really having trouble with rendering  14400x9000px big element with 1500 differently positioned elements with children and hover/click events...

**Comment by denyslukovsc** [comment]
In theory it should be possible to implement clusterized horizontal list using this technique
https://css-tricks.com/pure-css-horizontal-scrolling/?utm_source=frontendfocus&utm_medium=email

**Comment by NeXTs** [comment]
In theory it should be possible to implement clusterized horizontal list using this technique
https://css-tricks.com/pure-css-horizontal-scrolling

**Comment by pchr-srf** [comment]
Very cool idea! We managed to solve it in a different way without using clusterize. Native + translate3d for that extra performance on IOS :)

**Comment by NeXTs** [comment]
@pchr-srf Hey, cool! Could you please explain if "few words" what do you meant saying Native?

**Comment by pchr-srf** [comment]
@NeXTs : Sure! I thought we had too much data/too many dom elements on the screen so the browsers had trouble rendering it fast enough on scrolling through the table. But it turned out that it was the old plugin we used (jQuery.kinetic) which made the movements too slow. I implemented my own inertia-drag-method (very closely related to https://ariya.io/2013/11/javascript-kinetic-scrolling-part-2) in vanilla JS and used some CSS magic (translate3d mostly) to improve performance on IOS.
