### ISSUE TITLE
redundant rerendering on first time scroll

### ISSUE THREAD

**Issue by kamax1** [NeXTs/Clusterize.js#83]
When scrolling the table for the first time the cluster rerenders and content has bad flashing effect. 

I investigated the problem. In my case problem in method getRowsHeight at line
`opts.item_height = nodes[Math.floor(nodes.length / 2)].offsetHeight;`
opts.item_height equals 0 during initialization (but nodes exists)
so method getClusterNum return Infinity because of division by zero

i've added hot fix 

```
    getClusterNum: function () {
      this.options.scroll_top = this.scroll_elem.scrollTop;
      if (this.options.cluster_height == this.options.block_height) return 0;
      return Math.floor(this.options.scroll_top / (this.options.cluster_height - this.options.block_height)) || 0;
    }
```

now it works fine for me. Would be cool if you can fix it right way.

I'm using clusterize as directive in Vuejs framework.

**Comment by NeXTs** [comment]
Hey

> opts.item_height equals 0 during initialization (but nodes exists)

how this could be possible if nodes exists?
could you please create example at codepen?

**Comment by kamax1** [comment]
Here is an example. http://codepen.io/anon/pen/ORNagp
I've figured out that it's caused by async loading of data and changing between different states.

**Comment by NeXTs** [comment]
Whoa, great catch @kamax1 !

**Comment by NeXTs** [comment]
Just pushed v0.17.1

Try this http://codepen.io/NeXTs/pen/GjkZON?editors=1010
Once cdn updates you could remove clusterize sources from my codepen and add script tag to cdn with v0.17.1

Pay attention how I changed html and `loaded`. If your version was important to you - use it, but there would be additional height determination (because until `loaded` is false - vue doesn't render table so Clusterize could not determine row's height. And will actually investigate row by triggering scroll (when obviously investigation of row height during .update is preferred))

**Comment by kamax1** [comment]
Thank you for the fast response. Works perfectly!
