### ISSUE TITLE
Example fails to demonstrate the benefit of using clusterize.js

### ISSUE THREAD

**Issue by exebook** [NeXTs/Clusterize.js#93]
First step: add 5000 rows and should feel laggy. But it does not feel laggy to me, feels extremely smooth.
Step: Initialize clusterize.js and should feel smoother. But it starts feeling extremely laggy.
All other steps -- it feels about the same as in previous step.

Ubuntu 16, Firefox 50.1.0, Acer Aspire R7

**Comment by NeXTs** [comment]
Hey
Heah, that's because FF implemented same feature natively, thay call it **[AZP](http://www.ghacks.net/2015/07/28/scrolling-in-firefox-to-get-a-lot-better-thanks-to-apz/)**
Last time I investigated this feature, it was experimental and may be enabled manually by setting config **layers.async-pan-zoom.enabled**

I had idea to disable clusterize if user's browser is FF with AZP enabled, but I [did not find convenient way to detect is AZP is enabled](http://stackoverflow.com/questions/35986448/determine-firefoxs-config-by-javascript)

btw huge list freezes FF even with enabled AZP during page initialization since browser has to render every list item, while clusterize don't

**Comment by NeXTs** [comment]
@exebook do you have idea how to handle this?
