### ISSUE TITLE
Bad Things happen with non-unique markup

### ISSUE THREAD

**Issue by yarf** [NeXTs/Clusterize.js#97]
If the markup for each row is not unique, bad things seem to happen. Here's a slightly adjusted version of your "search" example to demonstrate, where I removed the unique index from the inserted rows: http://codepen.io/anon/pen/MJxNqo

... scroll the table towards the bottom and watch what happens?

**Comment by NeXTs** [comment]
Hello
Hm, indeed
That's because [cache condition](https://github.com/NeXTs/Clusterize.js/blob/master/clusterize.js#L262) which was made to avoid unnecessary repaints (for example when call .update(data) while data didn't actually changed). That's a bug which should be fixed so thanks for letting me know but do you really have that much weird table with exact same rows? :)

**Comment by yarf** [comment]
using Clusterize to render a (potentially) large amount of "status" information ... there are often rows with identical status ;p

**Comment by yarf** [comment]
Thank-you!

**Comment by NeXTs** [comment]
@yarf oops, use v0.17.4 :)
